Demo webui for simbank
galasa-dev/simplatform pull request #74
Opened 2020-10-07 09:58 UTC by DianaSlepikaite

Signed-off-by: Diana Slepikaite <d.slepikaite@gmail.com>

2020-10-07 10:38 UTC, hobbit1983 requested changes
Thanks again for doing this Diana.  Awesome work.  Just some minor comments and corrections to clean up the final version.

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/BasicAccountCreditTest.java
> +     * accounti
spelling error?

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +		//Dianas code
can we remove personal comments please

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +		.positionCursorToFieldContaining("Userid").tab().type("IBMUSER")
we should use the credentials from core manager for the userid and password

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +		//Dianas code
cleanup

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +		//Charlies code
cleanup

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +		//Charlies code
ahem

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +	public static int account;
don't think this needs to be a static variable

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +		logger.info("batchJob.toString() = " +  batchJob.toString());
As long as the batch manager logs the JCL response to the RAS I don't think we need to log it

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +	public Log logger;
Might be nice to log what we are doing as the test progresses.  when we get an error then log a message to describe the problem

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simbank-tests/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java
> +		page.clickElementById("submit");
Can we take some screenshots of the page we are navigating so that they get stored in the RAS.

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simplatform-application/galasa-simplatform-3270/pom.xml
> +		<version>0.11.0-SNAPSHOT</version>
this should be 0.12.0-SNAPSHOT

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simplatform-application/galasa-simplatform-webapp/pom.xml
> +		<!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
can we remove the comment please

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simplatform-application/galasa-simplatform-webapp/pom.xml
> +			<version>2.8.6</version>
might need to check with Mike but I think the version numbers should be pulled from elsewhere so we use the same levels in all the repositories.

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simplatform-application/galasa-simplatform-webapp/src/main/java/SimbankServlet.java
> +		// TODO Auto-generated constructor stub
can we remove this please

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simplatform-application/galasa-simplatform-webapp/src/main/java/ResponseMessageObject.java
> +	@Expose
is there any harm in exposing the other values?

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simplatform-application/galasa-simplatform-webapp/src/main/webapp/WEB-INF/web.xml
> +  	<servlet-name>HelloTest</servlet-name>
can we give the servlet a better name

2020-10-07 10:38 UTC, hobbit1983 commented on galasa-simplatform-application/galasa-simplatform-webapp/src/main/webapp/index.html
> +<script type="text/javascript" src="script.js"></script>
I believe the script tag by convention should be in the header - but my HTML foo is rusty

2020-10-07 14:08 UTC, Jimbo4794 commented
I wouldnt worry about:
src/main/java/dev/galasa/simbank/tests/WebAppIntegrationTest.java 

As I have re-written this.

2020-10-14 15:46 UTC, hobbit1983 approved these changes

2020-10-14 15:54 UTC, merged